#!/usr/bin/env python

import boto3
import requests
import json
import time
import os
from io import BytesIO
import traceback
from predictor import inference
import flask
import threading


import logging

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# 🔧 Config
QUEUE_URL_RESULT = os.environ["SQS_SND_QUEUE_URL"]
QUEUE_URL = os.environ["SQS_REC_QUEUE_URL"]
REGION_NAME = os.getenv("AWS_REGION", "ca-central-1")
WAIT_TIME_SECONDS = int(os.getenv("WAIT_TIME_SECONDS", 10))
MAX_MESSAGES = int(os.getenv("MAX_MESSAGES", 1))
VISIBILITY_TIMEOUT = int(os.getenv("VISIBILITY_TIMEOUT", 30))

# AWS clients
sqs = boto3.client("sqs", region_name=REGION_NAME)

# The flask app for serving predictions
app = flask.Flask(__name__)

@app.route("/ping", methods=["GET"])
def ping():
    """Determine if the container is working and healthy. In this sample container, we declare
    it healthy if we can load the model successfully."""
#    health = ScoringService.get_model() is not None  # You can insert a health check here

 #   status = 200 if health else 404
    return flask.Response(response="\n", status=200, mimetype="application/json")


def get_ec2_instance_id():
    try:
        # Get IMDSv2 token (required in newer AWS regions)
        token_url = "http://169.254.169.254/latest/api/token"
        headers = {'X-aws-ec2-metadata-token-ttl-seconds': '21600'}
        token = requests.put(token_url, headers=headers, timeout=2).text

        # Fetch instance ID
        metadata_url = "http://169.254.169.254/latest/meta-data/instance-id"
        headers = {'X-aws-ec2-metadata-token': token}
        instance_id = requests.get(metadata_url, headers=headers, timeout=2).text
        
        return instance_id
    except Exception as e:
        print(f"Failed to get EC2 instance ID: {e}")
        return None

def send_result_message(message):
    sqs.send_message(
            QueueUrl=QUEUE_URL_RESULT,
            MessageBody=json.dumps(message)
    )

def process_message(message):
    try:
        logger.info(f"📤 Starting inference...")
        result = inference(message)
        logger.info(f"✅ Result: {result}")

        return result
    except Exception as e:
        logger.error(f"❌ Error processing message: {e}")
        logger.debug(traceback.format_exc())
        raise

def poll_queue():
    logger.info("🚀 Listening for messages...")
    while True:
        try:
            response = sqs.receive_message(
                QueueUrl=QUEUE_URL,
                MaxNumberOfMessages=MAX_MESSAGES,
                WaitTimeSeconds=WAIT_TIME_SECONDS,
                VisibilityTimeout=VISIBILITY_TIMEOUT,
            )

            messages = response.get("Messages", [])
            if not messages:
                continue

            for msg in messages:
                receipt_handle = msg["ReceiptHandle"]
                body = json.loads(msg["Body"])
                result = process_message(body)
                if result:
                    merge_rec_result = body | result | {"instance_id": get_ec2_instance_id()}
                    logger.info(f"📤 Sending JSON result to the queue: {merge_rec_result}")
                    send_result_message(merge_rec_result)
                    logger.info(f"✅ JSON result written to the queue")
                    sqs.delete_message(QueueUrl=QUEUE_URL, ReceiptHandle=receipt_handle)
                    logger.info("🗑️  Deleted message received")
                else:
                    logger.info("⚠️  Message left for retry")

            time.sleep(1)

        except Exception as e:
            print("Error caught:", e)

if __name__ == "__main__":
    threading.Thread(target=lambda: app.run(host="0.0.0.0", port=8080), daemon=True).start()
    poll_queue()