#!/usr/bin/env python

import boto3
import requests
import json
import os
import traceback
from predictor import inference
import flask
import threading
import time
import argparse
import base64

import logging

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# 🔧 Config
QUEUE_URL_RESULT = os.environ["SQS_SND_QUEUE_URL"]
REGION_NAME = os.getenv("AWS_REGION", "ca-central-1")

# AWS clients
sqs = boto3.client("sqs", region_name=REGION_NAME)

# The flask app for serving predictions
app = flask.Flask(__name__)

@app.route("/ping", methods=["GET"])
def ping():
    return flask.Response(
        response=json.dumps({}),
        status=200,
        mimetype="application/json"
    )

def send_result_message(message):
    sqs.send_message(
            QueueUrl=QUEUE_URL_RESULT,
            MessageBody=json.dumps(message)
    )

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--message-body', required=True)
    args = parser.parse_args()

    try:
        message_body = json.loads(base64.b64decode(args.message_body).decode())
        print(f"Processing job: {message_body}")
        
        logger.info(f"📤 Starting inference...")
        result = inference(message_body)
        logger.info(f"✅ Result: {result}")

        job_id = os.environ.get('AWS_BATCH_JOB_ID')

        if result:
            merge_rec_result = message_body | result | {"instance_id": job_id}
            logger.info(f"📤 Sending JSON result to the queue: {merge_rec_result}")
            send_result_message(merge_rec_result)
            logger.info(f"✅ JSON result written to the queue")
        else:
            logger.info("⚠️  Message left for retry")
        
    except Exception as e:
        logger.error(f"❌ Batch job failed: {e}")
        logger.error(traceback.format_exc())
        raise

if __name__ == "__main__":
  #  threading.Thread(target=lambda: app.run(host="0.0.0.0", port=8080), daemon=True).start()
    main()